#!/bin/sh
# Written by Gia H. Ngo and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

cd ~/storage
rsync -a --exclude .git CBIG_private/* Standalone_Yeo2015_AuthorTopic

# remove unused stable projects
rm -r Standalone_Yeo2015_AuthorTopic/stable_projects/brain_parcellation
rm -r Standalone_Yeo2015_AuthorTopic/stable_projects/disorder_subtypes
rm -r Standalone_Yeo2015_AuthorTopic/stable_projects/fMRI_dynamics
rm -r Standalone_Yeo2015_AuthorTopic/stable_projects/preprocessing
rm -r Standalone_Yeo2015_AuthorTopic/stable_projects/registration
rm -r Standalone_Yeo2015_AuthorTopic/stable_projects/meta-analysis/Ngo2019_AuthorTopic

# remove duplicated License generated by Github
rm Standalone_Yeo2015_AuthorTopic/LICENSE
